### ISSUE TITLE
Sliverstatus error in ready sliver

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#431] opened 2015-05-21 00:21 UTC
I have a slice testhello in project SampleClass and that has a sliver in PG Utah. 

From the slice page, when I click the individual button get status I get just the word error. 
(attached: slice-sliver-error.png)

If I press the resource status button, the page is querying the AM for ever and I can't get the raw sliver status. (attached: sliver-status-hang.png)

When I query with omni there is nothing wrong with my sliver, it is just ready
(attached: testhello-sliverstatus-www-emulab-net-protogeniv2.json)

 _Imported from trac ticket [#431](http://trac.gpolab.bbn.com/proto-ch/ticket/431),  created by nriga on 03-05-2013 at 09:16, last modified: 03-05-2013 at 16:30_

**Comment by innnkkki** [comment] 2015-05-21 00:21
_nriga (innnkkki) attached [sliver-status-hang.png](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/431/sliver-status-hang.png) on 03-05-2013 at 09:17_

**Comment by innnkkki** [comment] 2015-05-21 00:21
_nriga (innnkkki) attached [testhello-sliverstatus-www-emulab-net-protogeniv2.json](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/431/testhello-sliverstatus-www-emulab-net-protogeniv2.json) on 03-05-2013 at 09:17_

**Comment by innnkkki** [comment] 2015-05-21 00:21
_nriga (innnkkki) attached [slice-sliver-error.png](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/431/slice-sliver-error.png) on 03-05-2013 at 09:18_

**Comment by seledwards** [comment] 2015-05-21 00:21
_sedwards (seledwards) attached [apache_error.log](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/431/apache_error.log) on 03-05-2013 at 09:44_

**Comment by seledwards** [comment] 2015-05-21 00:21
Niky has renewed her sliver so we can test this.

Niky, what RSpec did you use?  

_Trac comment by sedwards (github user: seledwards) on 03-05-2013 at 09:36_

**Comment by seledwards** [comment] 2015-05-21 00:21
I found the log in error.log on panther.  I've attached the output.

It thinks it's not getting back valid JSON.

_Trac comment by sedwards (github user: seledwards) on 03-05-2013 at 09:45_

**Comment by seledwards** [comment] 2015-05-21 00:22
I believe the RSpec should be this one: http://www.gpolab.bbn.com/experiment-support/HelloGENI/hellogeni.rspec



_Trac comment by sedwards (github user: seledwards) on 03-05-2013 at 09:52_

**Comment by seledwards** [comment] 2015-05-21 00:22
I'm able to repeat this error using a cached copy of the hellogeni rspec and a slice name testhello2.

Also, `https://panther.gpolab.bbn.com/secure/amstatus.php?slice_id=bc26b541-fd15-4d65-b86d-2602e41726bf&am_id=14` returns:
```
[]
```

_Trac comment by sedwards (github user: seledwards) on 03-05-2013 at 09:58_

**Comment by seledwards** [comment] 2015-05-21 00:22
I think this may be a duplicate of #357.

Also note that I have used this RSpec previously (I'm pretty sure at PG Utah) and it worked fine.

_Trac comment by sedwards (github user: seledwards) on 03-05-2013 at 10:04_

**Comment by seledwards** [comment] 2015-05-21 00:22
Fascinating. I just got email from testbed-ops@flux.utah.edu:

```
Nodes:
 [pc516](Node:) [pcvm411-2](Node:)
in urn:publicid:IDN+panther:sele+slice+testhello2 failed.
```


_Trac comment by sedwards (github user: seledwards) on 03-05-2013 at 10:05_

**Comment by seledwards** [comment] 2015-05-21 00:22
Niky says she has seen this error email yesterday.  But she says her `testhello` slice did not have this problem.

_Trac comment by sedwards (github user: seledwards) on 03-05-2013 at 10:08_

**Comment by tcmitchell** [comment] 2015-05-21 00:22
This looks like it might be a bug in the ProtoGENI AM. Some mac addresses are returned in sliver status as type "double" instead of type "string". The double type causes omni to interpret the mac_address as infinity. The resulting JSON that gets into the portal has a token `Infinity`, which is not legal JSON. The root cause is the XML-RPC return value from the ProtoGENI AM on one of your two nodes. The other mac_address is properly typed as a string. We sent an inquiry to ProtoGENI asking them to investigate.

_Trac comment by tmitchel (github user: tcmitchell) on 03-05-2013 at 15:46_

**Comment by tcmitchell** [comment] 2015-05-21 00:22
ProtoGENI confirms that this was an error in their AM. MAC addresses that contain only numbers, followed by a single letter 'e', followed only by numbers could be interpreted by their XML-RPC encoder as exponential notation. This caused them to be marked as a double instead of a string in the resulting sliver status structure.

They have posted a fix to the Utah AM. Other ProtoGENI based aggregates will get this fix when they update.

_Trac comment by tmitchel (github user: tcmitchell) on 03-05-2013 at 16:27_

**Closed** 2015-05-21 00:22 UTC
Labels: clearinghouse, task
