### ISSUE TITLE
Test splitting services

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#174] opened 2015-05-20 20:46 UTC
- Diff DB instance for each service
 - Diff machine for each service

 _Imported from trac ticket [#174](http://trac.gpolab.bbn.com/proto-ch/ticket/174),  created by ahelsing on 06-25-2012 at 15:07, last modified: 08-21-2012 at 08:24_

**Comment by MarshallBrinn** [comment] 2015-05-20 20:47
This is a duplicate of 156

_Trac comment by mbrinn (github user: MarshallBrinn) on 08-21-2012 at 08:24_

**Closed** 2015-05-20 20:47 UTC
Labels: clearinghouse, duplicate, task
