### ISSUE TITLE
slice details page shows wrong login information for multiuser slivers

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#621] opened 2015-05-21 01:47 UTC
When i browse to [https://portal.geni.net/secure/listresources.php?slice_id=87d4977b-6fd3-4336-9cf7-0cbc920f42bc] (the slice details page for a slice owned by Sarah on which my account has privileges), the Login information box shows:
```
Login 	ssh sedwards@pc2.instageni.gpolab.bbn.com -p 31290
```
However, my key is actually installed in the "chaos" account on that VM, not the "sedwards" account.  So that command does not work for me, but:
```
ssh chaos@pc2.instageni.gpolab.bbn.com -p 31290
```
does work.

Would it be possible for the portal to show the correct username for the logged-in user, rather than the slice creator, in this case?

 _Imported from trac ticket [#621](http://trac.gpolab.bbn.com/proto-ch/ticket/621),  created by chaos on 06-14-2013 at 16:03, last modified: 06-14-2013 at 16:07_

**Comment by ahelsing** [comment] 2015-05-21 01:47
Fixed description; too much copy/paste.

_Trac comment by chaos on 06-14-2013 at 16:04_

**Comment by seledwards** [comment] 2015-05-21 01:47
Yes.  This is a duplicate of #510 which is (hopefully) on the docket for the upcoming release.

_Trac comment by sedwards (github user: seledwards) on 06-14-2013 at 16:07_

**Closed** 2015-05-21 01:47 UTC
Labels: duplicate, portal, task
