### ISSUE TITLE
Allow user to download ssh public key

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#360] opened 2015-05-20 23:47 UTC
There is a way to download the ssh private key, but not the ss public key. When using external tools, like omni, it would be desirable to be able to download the ssh public key so that the same ssh private key could be used on allocated resources.

This only affects users who ask the portal to generate an ssh keypair.

 _Imported from trac ticket [#360](http://trac.gpolab.bbn.com/proto-ch/ticket/360),  created by tmitchel on 12-05-2012 at 15:12, last modified: 06-26-2013 at 09:21_

**Comment by tcmitchell** [comment] 2015-05-20 23:47
Additionally, when this feature is added, update tool-omniconfig.php to include instructions for downloading the ssh public key for use in the downloaded omni config file.

_Trac comment by tmitchel (github user: tcmitchell) on 03-04-2013 at 09:45_

**Comment by seledwards** [comment] 2015-05-20 23:47
Niky asked for this again.

_Trac comment by sedwards (github user: seledwards) on 04-02-2013 at 09:19_

**Comment by ahelsing** [comment] 2015-05-20 23:48
Duplicate of #655

_Trac comment by bujcich on 06-26-2013 at 09:21_

**Closed by ahelsing** 2015-05-20 23:48 UTC
Labels: duplicate, portal, task
