### ISSUE TITLE
Createsliver returns error but portal does not realize and says Finished in Green

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#1406] opened 2015-07-09 20:08 UTC
SImple to reproduce. Allocate a node on an IG node. Then,  when done, allocate a second node on the same node. You get an error back (something like "Failed CreateSliver for slice urn:publicid:IDN+ch.geni.net:COUNT+slice+CHOCULA at cwru-ig. Error from Aggregate: code 7. protogeni AM code: 7: Must delete existing slice first (PG log url - look here for details on any failures: https://www.geni.case.edu/spewlogfile.php3?logfile=0d937643da49be18c54baaacff4e7105). But the Add resources (results) page shows a green FInished, not a red Error.

**Comment by ahelsing** [comment] 2015-07-09 21:23
I think this is a duplicate of: https://github.com/GENI-NSF/geni-portal/issues/1134

**Closed** 2015-07-10 15:54 UTC
