### ISSUE TITLE
Hide non compute AMs from Jacks

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1304] opened 2015-05-21 06:38 UTC
You cannot bind a site to a FOAM or AL2S or ION AM within Jacks. So listing those aggregates in Jacks just makes the dropdown harder to read and confuses experimenters.

Give Jacks only AMs marked as 'Compute'.

 _Imported from trac ticket [#1304](http://trac.gpolab.bbn.com/proto-ch/ticket/1304),  created by ahelsing on 02-12-2015 at 11:40, last modified: 02-23-2015 at 08:52_

**Comment by MarshallBrinn** [comment] 2015-05-21 06:38
Duplicate of #1316

_Trac comment by mbrinn (github user: MarshallBrinn) on 02-23-2015 at 08:52_

**Closed by MarshallBrinn** 2015-05-21 06:38 UTC
Labels: duplicate, enhancement, portal
