### ISSUE TITLE
Consider syslog for key events

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#108] opened 2015-05-20 20:19 UTC
Consider trying to send key events to syslog, to allow infra to do nightly log checking via syslog

 _Imported from trac ticket [#108](http://trac.gpolab.bbn.com/proto-ch/ticket/108),  created by ahelsing on 06-06-2012 at 14:48, last modified: 08-21-2012 at 08:11_

**Comment by tcmitchell** [comment] 2015-05-20 20:19
http://php.net/manual/en/function.syslog.php

_Trac comment by tmitchel (github user: tcmitchell) on 06-06-2012 at 15:49_

**Comment by MarshallBrinn** [comment] 2015-05-20 20:20
This is a duplicate of 190

_Trac comment by mbrinn (github user: MarshallBrinn) on 08-21-2012 at 08:11_

**Closed by MarshallBrinn** 2015-05-20 20:20 UTC
