### ISSUE TITLE
Allow uploading a new version of an RSpec

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#1035] opened 2015-05-21 04:38 UTC
Niky asks:

 Is it easy in the edit page of an rspec to also add an option of "Upload a new version"? This will just overwrite the old rspec

 _Imported from trac ticket [#1035](http://trac.gpolab.bbn.com/proto-ch/ticket/1035),  created by tmitchel on 05-21-2014 at 17:23, last modified: 05-29-2014 at 09:13_

**Comment by MarshallBrinn** [comment] 2015-05-21 04:39
This is a duplicate of #226, or at least, our fix for #226 includes this capability. Closing as Duplicate.

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-29-2014 at 09:13_

**Closed** 2015-05-21 04:39 UTC
Labels: duplicate, enhancement, portal
