### ISSUE TITLE
Log some portal AM actions

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#33] opened 2015-05-20 19:47 UTC
The portal should invoke the logging service on some AM actions like CreateSliver and DeleteSliver so that they show up in the slice history.

 _Imported from trac ticket [#33](http://trac.gpolab.bbn.com/proto-ch/ticket/33),  created by tmitchel on 05-23-2012 at 14:20, last modified: 08-21-2012 at 08:03_

**Comment by MarshallBrinn** [comment] 2015-05-20 19:47
This is duplicate of #191

_Trac comment by mbrinn (github user: MarshallBrinn) on 08-21-2012 at 08:03_

**Closed by MarshallBrinn** 2015-05-20 19:47 UTC
Labels: duplicate, portal, task
