### ISSUE TITLE
Make best effort renewal the default at the portal

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-portal#906] opened 2015-05-21 03:48 UTC
At th GEC18 coding sprint we decided on a best effort renewal behavior where the AMs will renew as much as they can if the renewal time is longer than the requested. 

The PG AMs have implemented this since 10/31/13 and the change is already in Omni, 
make the change in the portal as well. 

 _Imported from trac ticket [#906](http://trac.gpolab.bbn.com/proto-ch/ticket/906),  created by nriga on 12-02-2013 at 12:36, last modified: 02-20-2014 at 14:03_

**Comment by ahelsing** [comment] 2015-05-21 03:48
The Omni support is in v2.5 (unreleased).

Specs on the change: http://groups.geni.net/geni/wiki/GAPI_AM_API_DRAFT#ChangeSetR:AllowRenewtoextendsliversasmuchaspossible


_Trac comment by ahelsing on 12-02-2013 at 12:39_

**Comment by seledwards** [comment] 2015-05-21 03:48
This has come up again.

_Trac comment by sedwards (github user: seledwards) on 01-14-2014 at 14:59_

**Comment by ahelsing** [comment] 2015-05-21 03:48
duplicate of #969

_Trac comment by ahelsing on 02-20-2014 at 14:03_

**Closed by ahelsing** 2015-05-21 03:48 UTC
Labels: duplicate, portal, task
