### ISSUE TITLE
slice in expired project results in undefined index

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1032] opened 2015-05-21 04:37 UTC
I have a slice whose project has been expired.

The result is this:
```
[Wed May 21 10:27:17 2014] [error] [client 128.89.254.85] PHP Notice:  Undefined index: 383be941-56ae-42bb-b945-fb1c714fe197 in /var/www/secure/tool-slices.php on line 244, referer: https://portal.geni.net/secure/profile.php
```
That is the project_id being undefined.

Make code robust to this.

Separate question is whether you should be allowed to make a project expire before the expiration of any of the slices in the project?

 _Imported from trac ticket [#1032](http://trac.gpolab.bbn.com/proto-ch/ticket/1032),  created by ahelsing on 05-21-2014 at 10:49, last modified: 04-14-2015 at 10:37_

**Comment by MarshallBrinn** [comment] 2015-05-21 04:37
This is a duplicate of #1357.

_Trac comment by mbrinn (github user: MarshallBrinn) on 04-14-2015 at 10:37_

**Closed** 2015-05-21 04:37 UTC
Labels: duplicate, portal
