### ISSUE TITLE
Can not create slices from inside flack

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-portal#413] opened 2015-05-21 00:14 UTC
From Flack, doing 'Create Slice' returns 'Slice name not valid'

Is this a project name in the URN issue? Can pgch solve this?

 _Imported from trac ticket [#413](http://trac.gpolab.bbn.com/proto-ch/ticket/413),  created by sedwards on 02-21-2013 at 18:38, last modified: 03-04-2013 at 11:36_

**Comment by ahelsing** [comment] 2015-05-21 00:14
duplicate of ticket #236

_Trac comment by ahelsing on 03-04-2013 at 11:36_

**Closed by ahelsing** 2015-05-21 00:14 UTC
