### ISSUE TITLE
Email user when account is approved/denied

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#133] opened 2015-05-20 20:30 UTC
The home page says you get email when your account is approved or denied.
That's not true, but should be.
That email should indicate what Role you've been given, the implications, and what to do next.

 _Imported from trac ticket [#133](http://trac.gpolab.bbn.com/proto-ch/ticket/133),  created by ahelsing on 06-08-2012 at 10:52, last modified: 08-21-2012 at 08:18_

**Comment by MarshallBrinn** [comment] 2015-05-20 20:30
This is a duplicate of 186

_Trac comment by mbrinn (github user: MarshallBrinn) on 08-21-2012 at 08:18_

**Closed by MarshallBrinn** 2015-05-20 20:30 UTC
Labels: duplicate, ma, task
