### ISSUE TITLE
Make slice description editable

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#134] opened 2015-05-20 20:31 UTC
The slice description field is not editable.

That needs sa_client and sa_controller methods.
Then the portal can use that.

 _Imported from trac ticket [#134](http://trac.gpolab.bbn.com/proto-ch/ticket/134),  created by ahelsing on 06-08-2012 at 11:09, last modified: 11-13-2012 at 10:23_

**Comment by seledwards** [comment] 2015-05-20 20:31
This is a duplicate of #69.

_Trac comment by sedwards (github user: seledwards) on 11-13-2012 at 10:23_

**Closed by seledwards** 2015-05-20 20:31 UTC
Labels: duplicate, sa, task
