### ISSUE TITLE
Undefined value in print-text-helpers.php

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-portal#441] opened 2015-05-21 00:28 UTC
[Wed Mar 06 12:53:39 2013] [error] [client 38.97.229.161] PHP Notice:  Undefined index: value in /var/www/secure/print-text-helpers.php on line 296, referer: https://panther.gpolab.bbn.com/secure/slice.php?project_id=114366eb-a147-4e41-b507-4c98b70638da&slice_id=ddf2e21e-2dd6-40d4-ac28-f47108b5e114&member_id=

 _Imported from trac ticket [#441](http://trac.gpolab.bbn.com/proto-ch/ticket/441),  created by mbrinn on 03-06-2013 at 12:54, last modified: 03-06-2013 at 13:15_

**Comment by tcmitchell** [comment] 2015-05-21 00:28
Duplicate of #436

_Trac comment by tmitchel (github user: tcmitchell) on 03-06-2013 at 13:15_

**Closed by tcmitchell** 2015-05-21 00:28 UTC
Labels: clearinghouse, duplicate, task
