### ISSUE TITLE
tool-omniconfig default project doesn't match link

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1005] opened 2015-05-21 04:27 UTC
On tool-omniconfig (manual config of omni link), you get a project chooser. And there are links for your omni-config. The URL for the omni-config however uses the last project in the project dropdown, instead of the default / first project in the dropdown which is what is displayed before you pick a project.

 _Imported from trac ticket [#1005](http://trac.gpolab.bbn.com/proto-ch/ticket/1005),  created by ahelsing on 04-23-2014 at 10:23, last modified: 05-27-2014 at 12:26_

**Comment by ahelsing** [comment] 2015-05-21 04:27
_ahelsing attached [Screen Shot 2014-05-24 at 7.00.55 AM.png](http://trac.gpolab.bbn.com/proto-ch/attachment/ticket/1005/Screen Shot 2014-05-24 at 7.00.55 AM.png) on 05-24-2014 at 07:01_

**Comment by tcmitchell** [comment] 2015-05-21 04:27
I cannot reproduce this issue. The links for `portal_omni_config.php` match the default project in the chooser for me. And the downloaded `omni_config` matches as well. Assigning to Aaron for retest or instructions for reproducing the issue.

_Trac comment by tmitchel (github user: tcmitchell) on 05-23-2014 at 17:30_

**Comment by ahelsing** [comment] 2015-05-21 04:27
I went to Profile -> Configure Omni -> Download and Customize...
Screenshot of what I see is attached.

The link for the omni_config text is:
https://portal.geni.net/secure/portal_omni_config.php?project=phproj5&version=2.3.1

Note that the project name in the link is not the same as the dropdown box.

If I then pick a project in the dropdown box, the link is right, and stays right.

_Trac comment by ahelsing on 05-24-2014 at 07:05_

**Comment by tcmitchell** [comment] 2015-05-21 04:27
Interesting. I see a mismatch in portal.geni.net, but the two match on my development host. The code looked fine, but I was reading through the lens of matching link and menu.

_Trac comment by tmitchel (github user: tcmitchell) on 05-27-2014 at 08:17_

**Comment by tcmitchell** [comment] 2015-05-21 04:27
The default link was generated from the first project in the project_id list but the drop down option elements were generated from the (second) projects list. Use the same list (project_ids) for iteration on both. Also, eliminate a redundant call to `lookup_project_details`.

_Trac comment by tmitchel (github user: tcmitchell) on 05-27-2014 at 12:26_

**Closed** 2015-05-21 04:27 UTC
Labels: portal
