### ISSUE TITLE
Portal reports "Number of leads for slice must be exactly 1" when adding a member

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#1242] opened 2015-05-21 06:11 UTC
A user reported that when they tried to add a member to a slice in role member they got the error "Number of leads for slice must be exactly 1". The user was not adding a lead, nor were they removing a lead.

Trying to reproduce the problem I added a member to a slice on which I am lead and I got:
  Warning: [ARGUMENT] ARGUMENT_ERROR (Ill-formed argument of type UID field MEMBER_UID: project_id)

 _Imported from trac ticket [#1242](http://trac.gpolab.bbn.com/proto-ch/ticket/1242),  created by tmitchel on 12-01-2014 at 11:04, last modified: 12-03-2014 at 11:29_

**Comment by MarshallBrinn** [comment] 2015-05-21 06:11
I'll grab this one.

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-01-2014 at 11:48_

**Comment by MarshallBrinn** [comment] 2015-05-21 06:12
Tom put in some fixes that fixed the ARGUMENT_ERROR problems described below.

I am unable to reproduce the problem as described and expect there is something amiss in the reporting of the bug. Things seem to be working fine at least given the details we've been given. Suggest we leave this open for a while and see if we hear anything more about this.

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-01-2014 at 13:58_

**Comment by MarshallBrinn** [comment] 2015-05-21 06:12
Put some debug printout into do-edit-slice-members.php so we can see what's going on in this case. The code looks right (after Tom's fixes).

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-02-2014 at 09:35_

**Comment by ahelsing** [comment] 2015-05-21 06:12
Tommy says it works for him now.
Logs show:
```
[Wed Dec 03 11:07:09 2014] [error] [client 24.93.27.245] SMBR = Array\n(\n    [e321058a-0e39-45c5-ae37-3c0fe6776b4c] => 3\n    [e5c6c735-31ed-440d-b111-1ef2d80fd15c] => 2\n    [f0cdb1ea-af73-4cc6-818b-9831b66053b1] => 1\n)\n, referer: https://portal.geni.net/secure/edit-slice-member.php?slice_id=39526199-b49e-467e-a64e-af54cac2fe3c&project_id=1eb9a075-f436-4386-bc77-388c0e939e8b
[Wed Dec 03 11:07:09 2014] [error] [client 24.93.27.245] SELS = Array\n(\n    [f0cdb1ea-af73-4cc6-818b-9831b66053b1] => 1\n    [e5c6c735-31ed-440d-b111-1ef2d80fd15c] => 2\n    [e321058a-0e39-45c5-ae37-3c0fe6776b4c] => 3\n    [e1fc982f-c12e-43d1-8f95-46a85308ce40] => 0\n    [a95a46ff-07a0-4429-8d76-79b2a2de93dd] => 0\n    [a4abb8c5-0282-4435-8d8d-75c59eb8f648] => 0\n    [b079c7b4-df47-403e-8008-5324f5cf8f06] => 0\n    [2d03f73a-7dfb-4821-868d-a98103d26f01] => 0\n    [b223f364-125b-462a-9569-16cc25490bdf] => 3\n    [9e5bad34-81b5-451f-b692-18e9b345e1d2] => 0\n    [0f79278b-f4fd-409c-a517-7cd1fc35af15] => 0\n    [580324f0-f52b-44b0-914f-d79d75284505] => 0\n)\n, referer: https://portal.geni.net/secure/edit-slice-member.php?slice_id=39526199-b49e-467e-a64e-af54cac2fe3c&project_id=1eb9a075-f436-4386-bc77-388c0e939e8b
[Wed Dec 03 11:07:09 2014] [error] [client 24.93.27.245] LEAD DETECTED : f0cdb1ea-af73-4cc6-818b-9831b66053b1 1, referer: https://portal.geni.net/secure/edit-slice-member.php?slice_id=39526199-b49e-467e-a64e-af54cac2fe3c&project_id=1eb9a075-f436-4386-bc77-388c0e939e8b
[Wed Dec 03 11:07:09 2014] [error] [client 24.93.27.245] LEAD_COUNT = 1, referer: https://portal.geni.net/secure/edit-slice-member.php?slice_id=39526199-b49e-467e-a64e-af54cac2fe3c&project_id=1eb9a075-f436-4386-bc77-388c0e939e8b
[Wed Dec 03 11:08:22 2014] [error] [client 24.93.27.245] SMBR = Array\n(\n    [e5c6c735-31ed-440d-b111-1ef2d80fd15c] => 2\n    [f0cdb1ea-af73-4cc6-818b-9831b66053b1] => 1\n)\n, referer: https://portal.geni.net/secure/edit-slice-member.php?slice_id=00730c9b-c76b-46aa-90ae-77beee65e6fe&project_id=1eb9a075-f436-4386-bc77-388c0e939e8b
[Wed Dec 03 11:08:22 2014] [error] [client 24.93.27.245] SELS = Array\n(\n    [f0cdb1ea-af73-4cc6-818b-9831b66053b1] => 1\n    [e5c6c735-31ed-440d-b111-1ef2d80fd15c] => 2\n    [e1fc982f-c12e-43d1-8f95-46a85308ce40] => 0\n    [a95a46ff-07a0-4429-8d76-79b2a2de93dd] => 0\n    [a4abb8c5-0282-4435-8d8d-75c59eb8f648] => 0\n    [b079c7b4-df47-403e-8008-5324f5cf8f06] => 0\n    [2d03f73a-7dfb-4821-868d-a98103d26f01] => 0\n    [e321058a-0e39-45c5-ae37-3c0fe6776b4c] => 0\n    [b223f364-125b-462a-9569-16cc25490bdf] => 0\n    [9e5bad34-81b5-451f-b692-18e9b345e1d2] => 0\n    [0f79278b-f4fd-409c-a517-7cd1fc35af15] => 0\n    [580324f0-f52b-44b0-914f-d79d75284505] => 3\n)\n, referer: https://portal.geni.net/secure/edit-slice-member.php?slice_id=00730c9b-c76b-46aa-90ae-77beee65e6fe&project_id=1eb9a075-f436-4386-bc77-388c0e939e8b
[Wed Dec 03 11:08:22 2014] [error] [client 24.93.27.245] LEAD DETECTED : f0cdb1ea-af73-4cc6-818b-9831b66053b1 1, referer: https://portal.geni.net/secure/edit-slice-member.php?slice_id=00730c9b-c76b-46aa-90ae-77beee65e6fe&project_id=1eb9a075-f436-4386-bc77-388c0e939e8b
[Wed Dec 03 11:08:22 2014] [error] [client 24.93.27.245] LEAD_COUNT = 1, referer: https://portal.geni.net/secure/edit-slice-member.php?slice_id=00730c9b-c76b-46aa-90ae-77beee65e6fe&project_id=1eb9a075-f436-4386-bc77-388c0e939e8b
[Wed Dec 03 11:08:32 2014] [error] [client 24.93.27.245] SMBR = Array\n(\n    [580324f0-f52b-44b0-914f-d79d75284505] => 3\n    [e5c6c735-31ed-440d-b111-1ef2d80fd15c] => 2\n    [f0cdb1ea-af73-4cc6-818b-9831b66053b1] => 1\n)\n, referer: https://portal.geni.net/secure/edit-slice-member.php?slice_id=00730c9b-c76b-46aa-90ae-77beee65e6fe&project_id=1eb9a075-f436-4386-bc77-388c0e939e8b
[Wed Dec 03 11:08:32 2014] [error] [client 24.93.27.245] SELS = Array\n(\n    [f0cdb1ea-af73-4cc6-818b-9831b66053b1] => 1\n    [e5c6c735-31ed-440d-b111-1ef2d80fd15c] => 2\n    [580324f0-f52b-44b0-914f-d79d75284505] => 0\n    [e1fc982f-c12e-43d1-8f95-46a85308ce40] => 0\n    [b079c7b4-df47-403e-8008-5324f5cf8f06] => 0\n    [a4abb8c5-0282-4435-8d8d-75c59eb8f648] => 0\n    [a95a46ff-07a0-4429-8d76-79b2a2de93dd] => 0\n    [2d03f73a-7dfb-4821-868d-a98103d26f01] => 0\n    [e321058a-0e39-45c5-ae37-3c0fe6776b4c] => 0\n    [b223f364-125b-462a-9569-16cc25490bdf] => 0\n    [9e5bad34-81b5-451f-b692-18e9b345e1d2] => 0\n    [0f79278b-f4fd-409c-a517-7cd1fc35af15] => 0\n)\n, referer: https://portal.geni.net/secure/edit-slice-member.php?slice_id=00730c9b-c76b-46aa-90ae-77beee65e6fe&project_id=1eb9a075-f436-4386-bc77-388c0e939e8b
[Wed Dec 03 11:08:32 2014] [error] [client 24.93.27.245] LEAD DETECTED : f0cdb1ea-af73-4cc6-818b-9831b66053b1 1, referer: https://portal.geni.net/secure/edit-slice-member.php?slice_id=00730c9b-c76b-46aa-90ae-77beee65e6fe&project_id=1eb9a075-f436-4386-bc77-388c0e939e8b
[Wed Dec 03 11:08:32 2014] [error] [client 24.93.27.245] LEAD_COUNT = 1, referer: https://portal.geni.net/secure/edit-slice-member.php?slice_id=00730c9b-c76b-46aa-90ae-77beee65e6fe&project_id=1eb9a075-f436-4386-bc77-388c0e939e8b
```


_Trac comment by ahelsing on 12-03-2014 at 11:16_

**Comment by MarshallBrinn** [comment] 2015-05-21 06:12
Need to remove the debug print-out that we enabled for previous release.

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-03-2014 at 11:22_

**Comment by MarshallBrinn** [comment] 2015-05-21 06:12
Debug printouts have been removed, tested and checked into develop. The original reported problem is gone so closing this ticket.

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-03-2014 at 11:29_

**Closed by MarshallBrinn** 2015-05-21 06:12 UTC
Labels: portal
