### ISSUE TITLE
map files should use SERVER_NAME not HTTP_HOST

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-portal#816] opened 2015-05-21 03:15 UTC
Several map files ([map-small.html](browser:portal/www/common/map/map-small.html), [map-big.html](browser:portal/www/common/map/1080display/map-big.html), [map.html](browser:portal/www/portal/map.html)) use HTTP_HOST when they should use SERVER_NAME. HTTP_HOST is set by the client, SERVER_NAME is set by the server. The latter is more reliable.

Additionally, why are these "HTML" files when they have PHP embedded? They should be renamed with a `php` extension if they have PHP.

 _Imported from trac ticket [#816](http://trac.gpolab.bbn.com/proto-ch/ticket/816),  created by tmitchel on 09-26-2013 at 10:25, last modified: 02-21-2014 at 10:44_

**Comment by ahelsing** [comment] 2015-05-21 03:15
Isn't this a duplicate of something we fixed?

_Trac comment by ahelsing on 02-20-2014 at 14:07_

**Comment by tcmitchell** [comment] 2015-05-21 03:16
Duplicate of issue #962 which was fixed for milestone:2.8.

_Trac comment by tmitchel (github user: tcmitchell) on 02-21-2014 at 10:44_

**Closed** 2015-05-21 03:16 UTC
Labels: duplicate, portal
